delay_evaluation: 3
# max_duration: 20
max_duration: 250 # corresponds to one tour
# max_duration: 5
min_depth: 0.5 
starting_height: 1
max_distance: 150
# ba_params: behavior_arbitration_no_goal.xml
# starting_positions: [[0,0],[0,12],[0,24],[0,36],[-5,37],[-15,37],[-23,37],[-10,37],[-31,36],[-37,36],[-45,36],[-55,36],[-56,24],[-57,12],[-57,7],[-57,3],[-57,0],[-57,-2],[-53,-3.5],[-50,-3.5],[-47,-3.5],[-44,-3.5],[-40,-3.5],[-37,-3.5],[-34,-3.6],[-30,-3.78],[-27,-3.92],[-24,-4.06],[-20,-4.2],[-17,-4.34],[-14,-4.48],[-10,-4.62],[-7,-4.76],[-4,-4.9],[-1,-5.1]]
starting_positions: [[-50,-3.0,0]]
waypoints: [[-30.8,-4],[-20.8,-4],[-5,-5],[-2.7,-5.2],[-0.27,-4.43],[-0.,-0.],[-0.176127,8.52094],[-0.336142,15.8637],[-0.174103,23.6654],[-0.424533,30.5467],[-0.6,35],[-0.75,36.48],[-2.75,36.95],[-9.19702,36.7426],[-15.5384,36.5405],[-23.0785,36.5471],[-45.4312,36.3484],[-50.8951,36.5703],[-53.38,37.14],[-56,35.32],[-57.5,31.6],[-57.5,20],[-57.5,10],[-57.5,5],[-57.99,-0.75],[-56.62,-3.],[-54,-3]]
goto_weight: 0.9